### ISSUE TITLE
not-gloss-examples on Hackage not building

### ISSUE THREAD

**Issue by guaraqe** [ghorn/not-gloss#16]
Hey, sorry for bothering you once more. The examples on Hackage do not build anymore with the new version. I see the version here on github is higher and that the code changed accordingly, would it be possible to put it on Hackage also? Thanks!

**Comment by ghorn** [comment]
no problem, I'll get to it tomorrow

**Comment by ghorn** [comment]
This release should fix it: http://hackage.haskell.org/package/not-gloss-examples-0.5.1.1
