### ISSUE TITLE
Helper functions for translation and rotation?

### ISSUE THREAD

**Issue by ChristopherKing42** [ghorn/not-gloss#20]
I think it would be nice if we had some helper functions. For example, `translateX`, `translateY`, `translateZ` and `rotateX`, `rotateY`, and `rotateZ`, for both `Vis.VisObject a` and `Vis.Camera`.

If you think its a good idea, I could even implement myself probably.

**Comment by ghorn** [comment]
Sorry this is so late, I realized my github notifications aren't working and I'm going through the backlog.

Rotation functions exist in the `spatial-math` package: https://hackage.haskell.org/package/spatial-math-0.4.0.0/docs/SpatialMath.html#v:rotateXyzAboutX

Translation can be fairly easily done inline, for instance `somePoint + V3 delta 0 0` is a `translateX`. I'll close this issue but feel free to make a merge request at https://github.com/ghorn/spatial-math
