### ISSUE TITLE
Syntax error in Haddock

### ISSUE THREAD

**Issue by peti** [ghorn/not-gloss#8]
Citing from http://hydra.cryp.to/build/527138/nixlog/2/raw:

    Running Haddock for not-gloss-0.7.0.0...
    Running hscolour for not-gloss-0.7.0.0...
    Preprocessing library not-gloss-0.7.0.0...
    Preprocessing library not-gloss-0.7.0.0...

    Vis/Vis.hs:25:5:
        parse error on input ‘-- ^ optional background color’

**Comment by ghorn** [comment]
fixed in https://github.com/ghorn/not-gloss/commit/2f3c3b8e005e9e459a657bccfba2ebb939422d86
